-- schema.sql
-- Run this entire script in your Supabase SQL Editor to set up your project tables.

-- 1. Create the `patients` table
CREATE TABLE public.patients (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    dietitian_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    age INTEGER,
    gender TEXT,
    height NUMERIC,
    weight NUMERIC,
    phone TEXT,
    email TEXT,
    medical_history TEXT,
    current_medications TEXT,
    allergies TEXT,
    activity_level TEXT,
    sleep_pattern TEXT,
    water_intake TEXT,
    bowel_movements TEXT,
    agni TEXT,
    prakriti TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and create policies for `patients`
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Dietitians can view their own patients" 
ON public.patients FOR SELECT 
USING (auth.uid() = dietitian_id);

CREATE POLICY "Dietitians can insert their own patients" 
ON public.patients FOR INSERT 
WITH CHECK (auth.uid() = dietitian_id);

CREATE POLICY "Dietitians can update their own patients" 
ON public.patients FOR UPDATE 
USING (auth.uid() = dietitian_id);

-- 2. Create the `foods` table
CREATE TABLE public.foods (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    serving_size TEXT,
    calories NUMERIC,
    protein_g NUMERIC,
    carbs_g NUMERIC,
    fat_g NUMERIC,
    fiber_g NUMERIC,
    rasa TEXT[],
    guna TEXT[],
    virya TEXT,
    vata_effect TEXT,
    pitta_effect TEXT,
    kapha_effect TEXT,
    meal_type TEXT[],
    food_category TEXT,
    tags TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for foods (Optional: allow all authenticated users to read)
ALTER TABLE public.foods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read foods" ON public.foods FOR SELECT TO authenticated USING (true);

-- 3. Create the `diet_charts` table
CREATE TABLE public.diet_charts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id UUID REFERENCES public.patients(id) ON DELETE CASCADE,
    dietitian_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    goal TEXT,
    duration_weeks INTEGER,
    calories_target NUMERIC,
    meal_preferences TEXT[],
    exclusions TEXT[],
    special_instructions TEXT,
    plan_details JSONB,
    status TEXT DEFAULT 'active' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and create policies for `diet_charts`
ALTER TABLE public.diet_charts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Dietitians can view their own diet charts" 
ON public.diet_charts FOR SELECT 
USING (auth.uid() = dietitian_id);

CREATE POLICY "Dietitians can insert their own diet charts" 
ON public.diet_charts FOR INSERT 
WITH CHECK (auth.uid() = dietitian_id);

CREATE POLICY "Dietitians can update their own diet charts" 
ON public.diet_charts FOR UPDATE 
USING (auth.uid() = dietitian_id);

-- Optional: Create an `updated_at` trigger for patients
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_patients_modtime
BEFORE UPDATE ON public.patients
FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
